[workspace]
members = ["core", "boards/pico", "boards/esp32-s3-devkit-c-1"]
default-members = ["core", "boards/pico"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Ane Johanson", "Willem Roovers"]
description = "Display custom animations on IKEA's OBEGRÄNSAD using Rust on the Raspberry Pi Pico"
edition = "2024"

[workspace.dependencies]
embedded-hal = "1.0"
fugit = "0.5"
rand = { version = "0.10", default-features = false }
rand_xoshiro = "0.8"
