name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '14 3 1 * *'  # Monthly on the 1st at 03:14 UTC
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: fmt, check, build, clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
          targets: thumbv6m-none-eabi

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check
        run: cargo check --release --locked

      - name: Check linting
        run: cargo clippy --release --locked -- -D warnings

      - name: Build
        run: cargo build --release --locked
